# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MR Power Apps Workshop
email: april.a.speight@gmail.com
description: Mixed Reality Power Apps workshop.
baseurl: "/workshop-mr-powerapps" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-image-url: images/armchair.png
font-awesome-icon-logo:

# Social settings
github_username: aprilspeight
twitter_username: vogueandcode

# Build settings
markdown: kramdown

# Layout settings
home-link-in-menu: yes
